/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    campuses: Campus;
    'campus-applications': CampusApplication;
    transactions: Transaction;
    media: Media;
    blogs: Blog;
    members: Member;
    activities: Activity;
    tags: Tag;
    tenants: Tenant;
    'tenant-applications': TenantApplication;
    'menu-items': MenuItem;
    'time-slots': TimeSlot;
    carts: Cart;
    'cart-items': CartItem;
    orders: Order;
    'order-items': OrderItem;
    reviews: Review;
    events: Event;
    'event-registrations': EventRegistration;
    teams: Team;
    'team-vacancies': TeamVacancy;
    'team-applications': TeamApplication;
    'user-skills': UserSkill;
    'lost-found-items': LostFoundItem;
    'lf-match-sessions': LfMatchSession;
    'lf-chat-messages': LfChatMessage;
    majors: Major;
    'career-paths': CareerPath;
    'career-skills': CareerSkill;
    'user-career-progress': UserCareerProgress;
    'admin-actions': AdminAction;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    campuses: CampusesSelect<false> | CampusesSelect<true>;
    'campus-applications': CampusApplicationsSelect<false> | CampusApplicationsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-applications': TenantApplicationsSelect<false> | TenantApplicationsSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'time-slots': TimeSlotsSelect<false> | TimeSlotsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'team-vacancies': TeamVacanciesSelect<false> | TeamVacanciesSelect<true>;
    'team-applications': TeamApplicationsSelect<false> | TeamApplicationsSelect<true>;
    'user-skills': UserSkillsSelect<false> | UserSkillsSelect<true>;
    'lost-found-items': LostFoundItemsSelect<false> | LostFoundItemsSelect<true>;
    'lf-match-sessions': LfMatchSessionsSelect<false> | LfMatchSessionsSelect<true>;
    'lf-chat-messages': LfChatMessagesSelect<false> | LfChatMessagesSelect<true>;
    majors: MajorsSelect<false> | MajorsSelect<true>;
    'career-paths': CareerPathsSelect<false> | CareerPathsSelect<true>;
    'career-skills': CareerSkillsSelect<false> | CareerSkillsSelect<true>;
    'user-career-progress': UserCareerProgressSelect<false> | UserCareerProgressSelect<true>;
    'admin-actions': AdminActionsSelect<false> | AdminActionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username: string;
  fullName: string;
  /**
   * Jurusan, dipakai Career Compass
   */
  major?: string | null;
  /**
   * NIM, buat verifikasi email kampus
   */
  studentId?: string | null;
  /**
   * Clerk User ID for syncing
   */
  clerkId?: string | null;
  /**
   * User roles based on Blueprint
   */
  roles?: ('super-admin' | 'admin' | 'campus_admin' | 'partner_tenant' | 'partner_eo' | 'student')[] | null;
  /**
   * Campus managed by this user (only for campus_admin)
   */
  managedCampus?: (number | null) | Campus;
  /**
   * Campus where this user belongs (for students)
   */
  campus?: (number | null) | Campus;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses".
 */
export interface Campus {
  id: number;
  /**
   * Kode kampus unik, misal: UBM-ANCOL
   */
  code: string;
  /**
   * Nama lengkap kampus, misal: Universitas Bunda Mulia - Kampus Ancol
   */
  name: string;
  address: string;
  /**
   * Koordinat lokasi kampus (opsional)
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  campusType?: string | null;
  totalStudents?: number | null;
  picName?: string | null;
  picEmail?: string | null;
  picPhone?: string | null;
  logo?: (number | null) | Media;
  npwp?: string | null;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  websiteUrl?: string | null;
  applicationId?: (number | null) | CampusApplication;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-applications".
 */
export interface CampusApplication {
  id: number;
  /**
   * Status pendaftaran kampus
   */
  status: 'pending' | 'approved' | 'rejected';
  campusName: string;
  /**
   * Kode unik kampus (contoh: UBM-ANCOL)
   */
  campusCode: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  /**
   * Jenis institusi pendidikan
   */
  campusType: 'university' | 'institute' | 'college' | 'polytechnic' | 'academy';
  /**
   * Akreditasi kampus
   */
  accreditation?: ('A' | 'B' | 'C' | 'excellent' | 'good' | 'superior') | null;
  /**
   * Estimasi jumlah mahasiswa aktif
   */
  totalStudents?: number | null;
  /**
   * Person in Charge dari pihak kampus
   */
  applicantName: string;
  /**
   * Jabatan di kampus
   */
  applicantPosition: string;
  applicantEmail: string;
  applicantPhone: string;
  idCardNumber: string;
  /**
   * Nomor Pokok Wajib Pajak institusi
   */
  campusNpwp?: string | null;
  bankName: 'BCA' | 'MANDIRI' | 'BNI' | 'BRI' | 'CIMB' | 'PERMATA' | 'DANAMON' | 'BTN' | 'BSI' | 'OTHER';
  bankAccountNumber: string;
  bankAccountName: string;
  /**
   * URL website resmi kampus
   */
  websiteUrl?: string | null;
  /**
   * Deskripsi singkat tentang kampus
   */
  description?: string | null;
  /**
   * Perkiraan jumlah kantin/tenant yang akan bergabung
   */
  expectedTenants?: number | null;
  campusLogo: number | Media;
  idCardPhoto: number | Media;
  npwpPhoto?: (number | null) | Media;
  /**
   * Foto gedung kampus (min 2 foto)
   */
  campusPhotos: (number | Media)[];
  /**
   * Surat permohonan kerjasama (PDF/DOC)
   */
  officialLetter: number | Media;
  /**
   * Nomor Pokok Sekolah Nasional atau nomor induk lainnya
   */
  npsn?: string | null;
  /**
   * Dokumen akreditasi kampus
   */
  accreditationCertificate?: (number | null) | Media;
  additionalDocuments?: (number | Media)[] | null;
  clerkUserId?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  approvalNotes?: string | null;
  rejectionReason?:
    | ('incomplete_documents' | 'invalid_documents' | 'not_accredited' | 'requirements_not_met' | 'duplicate' | 'other')
    | null;
  createdCampusId?: (number | null) | Campus;
  createdAdminId?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Subdomain/URL (e.g. [yourstore].nexora.com)
   */
  slug: string;
  /**
   * Lokasi kampus tenant beroperasi
   */
  campus: number | Campus;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Detail lokasi (contoh: canteen Lt. 2 Stan No. 04)
   */
  locationDetail?: string | null;
  /**
   * No WhatsApp Tenant
   */
  phone?: string | null;
  openTime?: string | null;
  closeTime?: string | null;
  isOpen?: boolean | null;
  /**
   * ID Merchant DOKU untuk pembayaran
   */
  dokuMerchantId?: string | null;
  ownerName?: string | null;
  ownerEmail?: string | null;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  npwpNumber?: string | null;
  idCardNumber?: string | null;
  clerkUserId?: string | null;
  applicationId?: (number | null) | TenantApplication;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-applications".
 */
export interface TenantApplication {
  id: number;
  /**
   * Status pendaftaran
   */
  status: 'pending' | 'approved' | 'rejected';
  tenantName: string;
  /**
   * URL slug (auto-generated dari nama tenant)
   */
  slug: string;
  /**
   * Kampus lokasi beroperasi
   */
  campus: number | Campus;
  /**
   * Detail lokasi dalam kampus
   */
  locationDetail: string;
  applicantName: string;
  applicantEmail: string;
  phone: string;
  idCardNumber: string;
  /**
   * Nomor Pokok Wajib Pajak (jika ada)
   */
  npwpNumber?: string | null;
  /**
   * Bank untuk transfer pembayaran
   */
  bankName: 'BCA' | 'MANDIRI' | 'BNI' | 'BRI' | 'CIMB' | 'PERMATA' | 'DANAMON' | 'BTN' | 'BSI' | 'OTHER';
  bankAccountNumber: string;
  bankAccountName: string;
  /**
   * Deskripsi singkat tentang tenant
   */
  description?: string | null;
  /**
   * Menu signature yang dijual
   */
  menuSample?: string | null;
  /**
   * Contoh: Rp 10.000 - Rp 50.000
   */
  priceRange?: string | null;
  /**
   * Upload foto KTP pemilik
   */
  idCardPhoto: number | Media;
  /**
   * Upload foto NPWP (opsional)
   */
  npwpPhoto?: (number | null) | Media;
  /**
   * Foto tempat usaha
   */
  tenantPhoto: number | Media;
  /**
   * Surat pernyataan/izin dari pihak kampus (PDF/DOC)
   */
  businessPermitDocument: number | Media;
  /**
   * Dokumen pendukung lainnya (opsional)
   */
  additionalDocuments?: (number | Media)[] | null;
  /**
   * ID user dari Clerk (auto-filled)
   */
  clerkUserId?: string | null;
  /**
   * Admin yang melakukan review
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  /**
   * Catatan dari reviewer (alasan approve/reject)
   */
  approvalNotes?: string | null;
  /**
   * Alasan penolakan
   */
  rejectionReason?:
    | (
        | 'incomplete_documents'
        | 'invalid_documents'
        | 'invalid_location'
        | 'requirements_not_met'
        | 'duplicate'
        | 'other'
      )
    | null;
  /**
   * Reference ke tenant yang dibuat setelah approval
   */
  createdTenantId?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  invoiceNumber: string;
  /**
   * Terkait dengan pesanan canteen
   */
  order?: (number | null) | Order;
  /**
   * Terkait dengan pendaftaran Event
   */
  eventRegistration?: (number | null) | EventRegistration;
  paymentChannel?: string | null;
  amount: number;
  dokuTransactionId?: string | null;
  status: 'PENDING' | 'PAID' | 'FAILED' | 'EXPIRED';
  /**
   * Raw Webhook Response from DOKU
   */
  rawResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Nomor urut pesanan otomatis (contoh: NX-20260315-001).
   */
  orderNumber?: string | null;
  user: number | User;
  timeSlot: number | TimeSlot;
  status:
    | 'DRAFT'
    | 'PENDING_PAYMENT'
    | 'PAID'
    | 'CONFIRMED'
    | 'COOKING'
    | 'READY_FOR_PICKUP'
    | 'COMPLETED'
    | 'CANCELLED_EXPIRED'
    | 'CANCELLED_REFUNDED';
  subtotalAmount: number;
  platformFee: number;
  totalAmount: number;
  pickupCode?: string | null;
  qrVerificationHash?: string | null;
  notes?: string | null;
  lockedUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots".
 */
export interface TimeSlot {
  id: number;
  tenant?: (number | null) | Tenant;
  startTime: string;
  endTime: string;
  /**
   * Maksimal jumlah pesanan yang bisa diproses dalam slot ini
   */
  maxCapacity: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  user: number | User;
  ticketCode: string;
  qrHash: string;
  status: 'REGISTERED' | 'ATTENDED' | 'CANCELLED';
  checkedInAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Panitia/BEM/UKM
   */
  organizer: number | User;
  campus: number | Campus;
  title: string;
  category: string;
  description: string;
  poster: number | Media;
  eventStart: string;
  eventEnd: string;
  registrationDeadline: string;
  locationFormat: 'ONLINE' | 'OFFLINE' | 'HYBRID';
  locationDetail: string;
  ticketPrice: number;
  maxQuota: number;
  registeredCount: number;
  status: 'DRAFT' | 'PENDING_APPROVAL' | 'PUBLISHED' | 'REJECTED' | 'COMPLETED';
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  author: string;
  date: string;
  description: string;
  link: string;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * Format: YYYY
   */
  year: string;
  division: 'BPH' | 'Medkom' | 'Humas' | 'Litbang' | 'Advokasi';
  position: 'Ketua' | 'Wakil Ketua' | 'Sekretaris' | 'Bendahara' | 'Koordinator' | 'Wakil Koordinator' | 'Anggota';
  image: number | Media;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  date: string;
  description: string;
  tags: (number | Tag)[];
  /**
   * Instagram post link
   */
  instagram: string;
  link: string;
  thumbnail: number | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Contoh: compsci, ui-ux, bisnis, data-science, general
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  type: 'food' | 'drink' | 'snack' | 'dessert';
  basePrice: number;
  /**
   * Kuota Stok Harian
   */
  dailyStock?: number | null;
  stockStatus?: ('available' | 'low_stock' | 'out_of_stock') | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Menu tersedia untuk dipesan?
   */
  isAvailable?: boolean | null;
  /**
   * Grup Varian (Misal: Level Pedas, Extra Topping)
   */
  variantGroups?:
    | {
        name: string;
        isRequired?: boolean | null;
        allowMultiple?: boolean | null;
        minSelections?: number | null;
        maxSelections?: number | null;
        options: {
          name: string;
          extraPrice: number;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * 1 cart aktif per user per tenant
   */
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: number;
  cart: number | Cart;
  menuItem: number | MenuItem;
  quantity: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  menuItem: number | MenuItem;
  quantity: number;
  /**
   * Snapshot harga dasar saat order
   */
  unitBasePrice: number;
  selectedVariants:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  tenant?: (number | null) | Tenant;
  order: number | Order;
  user: number | User;
  menuItem: number | MenuItem;
  rating: number;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  leader: number | User;
  competitionName: string;
  fieldCategory: string;
  projectSynopsis: string;
  /**
   * Deadline tim harus lengkap
   */
  deadline: string;
  isClosed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-vacancies".
 */
export interface TeamVacancy {
  id: number;
  team: number | Team;
  /**
   * Contoh: UI/UX Designer
   */
  roleTitle: string;
  skillsRequired: {
    skill: string;
    id?: string | null;
  }[];
  slotsTotal: number;
  slotsFilled: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-applications".
 */
export interface TeamApplication {
  id: number;
  vacancy: number | TeamVacancy;
  applicant: number | User;
  portfolioUrl: string;
  pitchStatement: string;
  status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-skills".
 */
export interface UserSkill {
  id: number;
  user: number | User;
  skillName: string;
  proficiency?: ('pemula' | 'menengah' | 'mahir') | null;
  portfolioUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lost-found-items".
 */
export interface LostFoundItem {
  id: number;
  type: 'LOST' | 'FOUND';
  reporter: number | User;
  campus: number | Campus;
  itemName: string;
  category: string;
  description: string;
  locationDetail: string;
  dateTime: string;
  media?: (number | null) | Media;
  /**
   * Pertanyaan keamanan rahasia yang hanya diketahui pemilik (cth: 'Apa warna wallpaper HP?')
   */
  secretVerificationPrompt?: string | null;
  status: 'ACTIVE' | 'MATCH_PENDING' | 'RESOLVED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lf-match-sessions".
 */
export interface LfMatchSession {
  id: number;
  lostItem: number | LostFoundItem;
  foundItem: number | LostFoundItem;
  /**
   * 0 to 100
   */
  similarityScore: number;
  status: 'SUGGESTED' | 'CHAT_ACTIVE' | 'VERIFIED_MATCH' | 'REJECTED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lf-chat-messages".
 */
export interface LfChatMessage {
  id: number;
  session: number | LfMatchSession;
  sender: number | User;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "majors".
 */
export interface Major {
  id: number;
  /**
   * Contoh: Informatika, Sistem Informasi
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-paths".
 */
export interface CareerPath {
  id: number;
  major: number | Major;
  /**
   * Contoh: Software Engineer, Data Analyst
   */
  title: string;
  description?: string | null;
  /**
   * Dipakai untuk rekomendasi event relevan (dicocokkan ke tags di Events)
   */
  relatedTags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-skills".
 */
export interface CareerSkill {
  id: number;
  careerPath: number | CareerPath;
  skillName: string;
  /**
   * Kurasi sumber belajar/sertifikasi
   */
  resourceUrl?: string | null;
  isCertification?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-career-progress".
 */
export interface UserCareerProgress {
  id: number;
  user: number | User;
  careerSkill: number | CareerSkill;
  isCompleted?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-actions".
 */
export interface AdminAction {
  id: number;
  admin: number | User;
  actionType: 'approve_event' | 'reject_event' | 'moderate_lost_found' | 'suspend_tenant' | 'suspend_user' | 'other';
  /**
   * Contoh: 'events', 'lost-items'
   */
  targetCollection: string;
  targetId: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'campuses';
        value: number | Campus;
      } | null)
    | ({
        relationTo: 'campus-applications';
        value: number | CampusApplication;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-applications';
        value: number | TenantApplication;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'time-slots';
        value: number | TimeSlot;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: number | CartItem;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'team-vacancies';
        value: number | TeamVacancy;
      } | null)
    | ({
        relationTo: 'team-applications';
        value: number | TeamApplication;
      } | null)
    | ({
        relationTo: 'user-skills';
        value: number | UserSkill;
      } | null)
    | ({
        relationTo: 'lost-found-items';
        value: number | LostFoundItem;
      } | null)
    | ({
        relationTo: 'lf-match-sessions';
        value: number | LfMatchSession;
      } | null)
    | ({
        relationTo: 'lf-chat-messages';
        value: number | LfChatMessage;
      } | null)
    | ({
        relationTo: 'majors';
        value: number | Major;
      } | null)
    | ({
        relationTo: 'career-paths';
        value: number | CareerPath;
      } | null)
    | ({
        relationTo: 'career-skills';
        value: number | CareerSkill;
      } | null)
    | ({
        relationTo: 'user-career-progress';
        value: number | UserCareerProgress;
      } | null)
    | ({
        relationTo: 'admin-actions';
        value: number | AdminAction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  fullName?: T;
  major?: T;
  studentId?: T;
  clerkId?: T;
  roles?: T;
  managedCampus?: T;
  campus?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses_select".
 */
export interface CampusesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  address?: T;
  coordinates?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  campusType?: T;
  totalStudents?: T;
  picName?: T;
  picEmail?: T;
  picPhone?: T;
  logo?: T;
  npwp?: T;
  bankName?: T;
  bankAccountNumber?: T;
  bankAccountName?: T;
  websiteUrl?: T;
  applicationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-applications_select".
 */
export interface CampusApplicationsSelect<T extends boolean = true> {
  status?: T;
  campusName?: T;
  campusCode?: T;
  address?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  campusType?: T;
  accreditation?: T;
  totalStudents?: T;
  applicantName?: T;
  applicantPosition?: T;
  applicantEmail?: T;
  applicantPhone?: T;
  idCardNumber?: T;
  campusNpwp?: T;
  bankName?: T;
  bankAccountNumber?: T;
  bankAccountName?: T;
  websiteUrl?: T;
  description?: T;
  expectedTenants?: T;
  campusLogo?: T;
  idCardPhoto?: T;
  npwpPhoto?: T;
  campusPhotos?: T;
  officialLetter?: T;
  npsn?: T;
  accreditationCertificate?: T;
  additionalDocuments?: T;
  clerkUserId?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  approvalNotes?: T;
  rejectionReason?: T;
  createdCampusId?: T;
  createdAdminId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  invoiceNumber?: T;
  order?: T;
  eventRegistration?: T;
  paymentChannel?: T;
  amount?: T;
  dokuTransactionId?: T;
  status?: T;
  rawResponse?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  date?: T;
  description?: T;
  link?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  division?: T;
  position?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  tags?: T;
  instagram?: T;
  link?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  campus?: T;
  description?: T;
  logo?: T;
  locationDetail?: T;
  phone?: T;
  openTime?: T;
  closeTime?: T;
  isOpen?: T;
  dokuMerchantId?: T;
  ownerName?: T;
  ownerEmail?: T;
  bankName?: T;
  bankAccountNumber?: T;
  bankAccountName?: T;
  npwpNumber?: T;
  idCardNumber?: T;
  clerkUserId?: T;
  applicationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-applications_select".
 */
export interface TenantApplicationsSelect<T extends boolean = true> {
  status?: T;
  tenantName?: T;
  slug?: T;
  campus?: T;
  locationDetail?: T;
  applicantName?: T;
  applicantEmail?: T;
  phone?: T;
  idCardNumber?: T;
  npwpNumber?: T;
  bankName?: T;
  bankAccountNumber?: T;
  bankAccountName?: T;
  description?: T;
  menuSample?: T;
  priceRange?: T;
  idCardPhoto?: T;
  npwpPhoto?: T;
  tenantPhoto?: T;
  businessPermitDocument?: T;
  additionalDocuments?: T;
  clerkUserId?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  approvalNotes?: T;
  rejectionReason?: T;
  createdTenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  basePrice?: T;
  dailyStock?: T;
  stockStatus?: T;
  description?: T;
  image?: T;
  isAvailable?: T;
  variantGroups?:
    | T
    | {
        name?: T;
        isRequired?: T;
        allowMultiple?: T;
        minSelections?: T;
        maxSelections?: T;
        options?:
          | T
          | {
              name?: T;
              extraPrice?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots_select".
 */
export interface TimeSlotsSelect<T extends boolean = true> {
  tenant?: T;
  startTime?: T;
  endTime?: T;
  maxCapacity?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  cart?: T;
  menuItem?: T;
  quantity?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  user?: T;
  timeSlot?: T;
  status?: T;
  subtotalAmount?: T;
  platformFee?: T;
  totalAmount?: T;
  pickupCode?: T;
  qrVerificationHash?: T;
  notes?: T;
  lockedUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  menuItem?: T;
  quantity?: T;
  unitBasePrice?: T;
  selectedVariants?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  user?: T;
  menuItem?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  organizer?: T;
  campus?: T;
  title?: T;
  category?: T;
  description?: T;
  poster?: T;
  eventStart?: T;
  eventEnd?: T;
  registrationDeadline?: T;
  locationFormat?: T;
  locationDetail?: T;
  ticketPrice?: T;
  maxQuota?: T;
  registeredCount?: T;
  status?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  ticketCode?: T;
  qrHash?: T;
  status?: T;
  checkedInAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  leader?: T;
  competitionName?: T;
  fieldCategory?: T;
  projectSynopsis?: T;
  deadline?: T;
  isClosed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-vacancies_select".
 */
export interface TeamVacanciesSelect<T extends boolean = true> {
  team?: T;
  roleTitle?: T;
  skillsRequired?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  slotsTotal?: T;
  slotsFilled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-applications_select".
 */
export interface TeamApplicationsSelect<T extends boolean = true> {
  vacancy?: T;
  applicant?: T;
  portfolioUrl?: T;
  pitchStatement?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-skills_select".
 */
export interface UserSkillsSelect<T extends boolean = true> {
  user?: T;
  skillName?: T;
  proficiency?: T;
  portfolioUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lost-found-items_select".
 */
export interface LostFoundItemsSelect<T extends boolean = true> {
  type?: T;
  reporter?: T;
  campus?: T;
  itemName?: T;
  category?: T;
  description?: T;
  locationDetail?: T;
  dateTime?: T;
  media?: T;
  secretVerificationPrompt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lf-match-sessions_select".
 */
export interface LfMatchSessionsSelect<T extends boolean = true> {
  lostItem?: T;
  foundItem?: T;
  similarityScore?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lf-chat-messages_select".
 */
export interface LfChatMessagesSelect<T extends boolean = true> {
  session?: T;
  sender?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "majors_select".
 */
export interface MajorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-paths_select".
 */
export interface CareerPathsSelect<T extends boolean = true> {
  major?: T;
  title?: T;
  description?: T;
  relatedTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-skills_select".
 */
export interface CareerSkillsSelect<T extends boolean = true> {
  careerPath?: T;
  skillName?: T;
  resourceUrl?: T;
  isCertification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-career-progress_select".
 */
export interface UserCareerProgressSelect<T extends boolean = true> {
  user?: T;
  careerSkill?: T;
  isCompleted?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-actions_select".
 */
export interface AdminActionsSelect<T extends boolean = true> {
  admin?: T;
  actionType?: T;
  targetCollection?: T;
  targetId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}