/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    members: Member;
    activities: Activity;
    tags: Tag;
    tenants: Tenant;
    'menu-items': MenuItem;
    'pickup-slots': PickupSlot;
    carts: Cart;
    'cart-items': CartItem;
    orders: Order;
    'order-items': OrderItem;
    reviews: Review;
    events: Event;
    'event-registrations': EventRegistration;
    teams: Team;
    'team-positions': TeamPosition;
    'team-applications': TeamApplication;
    'user-skills': UserSkill;
    'lost-items': LostItem;
    'found-items': FoundItem;
    'item-matches': ItemMatch;
    'item-chat-messages': ItemChatMessage;
    majors: Major;
    'career-paths': CareerPath;
    'career-skills': CareerSkill;
    'user-career-progress': UserCareerProgress;
    'admin-actions': AdminAction;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'pickup-slots': PickupSlotsSelect<false> | PickupSlotsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'team-positions': TeamPositionsSelect<false> | TeamPositionsSelect<true>;
    'team-applications': TeamApplicationsSelect<false> | TeamApplicationsSelect<true>;
    'user-skills': UserSkillsSelect<false> | UserSkillsSelect<true>;
    'lost-items': LostItemsSelect<false> | LostItemsSelect<true>;
    'found-items': FoundItemsSelect<false> | FoundItemsSelect<true>;
    'item-matches': ItemMatchesSelect<false> | ItemMatchesSelect<true>;
    'item-chat-messages': ItemChatMessagesSelect<false> | ItemChatMessagesSelect<true>;
    majors: MajorsSelect<false> | MajorsSelect<true>;
    'career-paths': CareerPathsSelect<false> | CareerPathsSelect<true>;
    'career-skills': CareerSkillsSelect<false> | CareerSkillsSelect<true>;
    'user-career-progress': UserCareerProgressSelect<false> | UserCareerProgressSelect<true>;
    'admin-actions': AdminActionsSelect<false> | AdminActionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username: string;
  fullName: string;
  /**
   * Jurusan, dipakai Career Compass
   */
  major?: string | null;
  /**
   * NIM, buat verifikasi email kampus
   */
  studentId?: string | null;
  /**
   * Publik hanya bisa memilih tenant/organizer/user saat sign up — lihat validate di bawah.
   */
  roles?: ('super-admin' | 'admin' | 'tenant' | 'organizer' | 'user')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Nama tenant/mitra
   */
  name: string;
  /**
   * This is the subdomain of your store (e.g. [yourstore].kana.com)
   */
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Titik lokasi di kampus
   */
  location?: string | null;
  openTime?: string | null;
  closeTime?: string | null;
  /**
   * Toggle manual buka/tutup
   */
  isOpen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  author: string;
  date: string;
  description: string;
  link: string;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * Format: YYYY
   */
  year: string;
  division: 'BPH' | 'Medkom' | 'Humas' | 'Litbang' | 'Advokasi';
  position: 'Ketua' | 'Wakil Ketua' | 'Sekretaris' | 'Bendahara' | 'Koordinator' | 'Wakil Koordinator' | 'Anggota';
  image: number | Media;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  date: string;
  description: string;
  tags: (number | Tag)[];
  /**
   * Instagram post link
   */
  instagram: string;
  link: string;
  thumbnail: number | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Contoh: compsci, ui-ux, bisnis, data-science, general
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  type: 'food' | 'drink' | 'snack' | 'dessert';
  price: number;
  /**
   * Stok tersisa
   */
  quantity?: number | null;
  stockStatus?: ('available' | 'low_stock' | 'out_of_stock') | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Nonaktifkan tanpa hapus
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-slots".
 */
export interface PickupSlot {
  id: number;
  tenant?: (number | null) | Tenant;
  slotStart: string;
  slotEnd: string;
  capacity?: number | null;
  bookedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * 1 cart aktif per user per tenant
   */
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: number;
  cart: number | Cart;
  menuItem: number | MenuItem;
  quantity: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Nomor urut pesanan per tenant per hari (reset tiap hari). Di-generate otomatis, bukan diisi manual.
   */
  orderNumber?: number | null;
  user: number | User;
  pickupSlot?: (number | null) | PickupSlot;
  total: number;
  status?: ('diterima' | 'dikonfirmasi' | 'sedang_dimasak' | 'siap_diambil' | 'selesai' | 'dibatalkan') | null;
  /**
   * Estimasi menit sampai siap
   */
  timeEstimate?: number | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  paymentMethod?: ('virtual_account' | 'qris' | 'e_wallet') | null;
  readyAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  menuItem: number | MenuItem;
  quantity: number;
  /**
   * Snapshot harga saat order
   */
  priceAtPurchase: number;
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  tenant?: (number | null) | Tenant;
  order: number | Order;
  user: number | User;
  menuItem: number | MenuItem;
  rating: number;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Panitia/BEM/UKM
   */
  organizer?: (number | null) | User;
  name: string;
  description?: string | null;
  type: 'competition' | 'seminar' | 'workshop' | 'other';
  scope: 'internal' | 'external';
  tags?: (number | Tag)[] | null;
  isOnline?: boolean | null;
  location?: string | null;
  poster?: (number | null) | Media;
  quota?: number | null;
  registrationDeadline: string;
  eventDate?: string | null;
  status?: ('draft' | 'pending_review' | 'published' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  user: number | User;
  ticketCode?: string | null;
  status?: ('registered' | 'checked_in' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  creator: number | User;
  /**
   * Nama lomba yang dituju
   */
  competitionName: string;
  /**
   * Bidang lomba (software dev, ui/ux, dsb)
   */
  field: string;
  description?: string | null;
  /**
   * Deadline tim harus lengkap
   */
  deadline: string;
  status?: ('open' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-positions".
 */
export interface TeamPosition {
  id: number;
  team: number | Team;
  /**
   * Contoh: UI/UX Designer
   */
  positionName: string;
  skillRequired?: string | null;
  slotsNeeded?: number | null;
  slotsFilled?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-applications".
 */
export interface TeamApplication {
  id: number;
  team: number | Team;
  position: number | TeamPosition;
  applicant: number | User;
  message?: string | null;
  status?: ('menunggu' | 'diterima' | 'ditolak') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-skills".
 */
export interface UserSkill {
  id: number;
  user: number | User;
  skillName: string;
  proficiency?: ('pemula' | 'menengah' | 'mahir') | null;
  portfolioUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lost-items".
 */
export interface LostItem {
  id: number;
  reporter: number | User;
  itemName: string;
  category: 'kartu_mahasiswa' | 'dompet' | 'elektronik' | 'botol_minum' | 'aksesoris' | 'lainnya';
  description?: string | null;
  lastSeenLocation?: string | null;
  lastSeenAt?: string | null;
  image?: (number | null) | Media;
  status?: ('dilaporkan' | 'ada_kecocokan' | 'dikonfirmasi' | 'dikembalikan') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "found-items".
 */
export interface FoundItem {
  id: number;
  finder: number | User;
  itemName: string;
  category: 'kartu_mahasiswa' | 'dompet' | 'elektronik' | 'botol_minum' | 'aksesoris' | 'lainnya';
  description?: string | null;
  foundLocation?: string | null;
  foundAt?: string | null;
  image?: (number | null) | Media;
  status?: ('dilaporkan' | 'ada_kecocokan' | 'dikonfirmasi' | 'dikembalikan') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-matches".
 */
export interface ItemMatch {
  id: number;
  lostItem: number | LostItem;
  foundItem: number | FoundItem;
  /**
   * Skor kemiripan kategori/lokasi/kata kunci
   */
  matchScore?: number | null;
  status?: ('disarankan' | 'dikonfirmasi' | 'ditolak') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-chat-messages".
 */
export interface ItemChatMessage {
  id: number;
  match: number | ItemMatch;
  sender: number | User;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "majors".
 */
export interface Major {
  id: number;
  /**
   * Contoh: Informatika, Sistem Informasi
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-paths".
 */
export interface CareerPath {
  id: number;
  major: number | Major;
  /**
   * Contoh: Software Engineer, Data Analyst
   */
  title: string;
  description?: string | null;
  /**
   * Dipakai untuk rekomendasi event relevan (dicocokkan ke tags di Events)
   */
  relatedTags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-skills".
 */
export interface CareerSkill {
  id: number;
  careerPath: number | CareerPath;
  skillName: string;
  /**
   * Kurasi sumber belajar/sertifikasi
   */
  resourceUrl?: string | null;
  isCertification?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-career-progress".
 */
export interface UserCareerProgress {
  id: number;
  user: number | User;
  careerSkill: number | CareerSkill;
  isCompleted?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-actions".
 */
export interface AdminAction {
  id: number;
  admin: number | User;
  actionType: 'approve_event' | 'reject_event' | 'moderate_lost_found' | 'suspend_tenant' | 'suspend_user' | 'other';
  /**
   * Contoh: 'events', 'lost-items'
   */
  targetCollection: string;
  targetId: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'pickup-slots';
        value: number | PickupSlot;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: number | CartItem;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'team-positions';
        value: number | TeamPosition;
      } | null)
    | ({
        relationTo: 'team-applications';
        value: number | TeamApplication;
      } | null)
    | ({
        relationTo: 'user-skills';
        value: number | UserSkill;
      } | null)
    | ({
        relationTo: 'lost-items';
        value: number | LostItem;
      } | null)
    | ({
        relationTo: 'found-items';
        value: number | FoundItem;
      } | null)
    | ({
        relationTo: 'item-matches';
        value: number | ItemMatch;
      } | null)
    | ({
        relationTo: 'item-chat-messages';
        value: number | ItemChatMessage;
      } | null)
    | ({
        relationTo: 'majors';
        value: number | Major;
      } | null)
    | ({
        relationTo: 'career-paths';
        value: number | CareerPath;
      } | null)
    | ({
        relationTo: 'career-skills';
        value: number | CareerSkill;
      } | null)
    | ({
        relationTo: 'user-career-progress';
        value: number | UserCareerProgress;
      } | null)
    | ({
        relationTo: 'admin-actions';
        value: number | AdminAction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  fullName?: T;
  major?: T;
  studentId?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  date?: T;
  description?: T;
  link?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  division?: T;
  position?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  tags?: T;
  instagram?: T;
  link?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  location?: T;
  openTime?: T;
  closeTime?: T;
  isOpen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  price?: T;
  quantity?: T;
  stockStatus?: T;
  description?: T;
  image?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-slots_select".
 */
export interface PickupSlotsSelect<T extends boolean = true> {
  tenant?: T;
  slotStart?: T;
  slotEnd?: T;
  capacity?: T;
  bookedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  cart?: T;
  menuItem?: T;
  quantity?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  user?: T;
  pickupSlot?: T;
  total?: T;
  status?: T;
  timeEstimate?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  readyAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  menuItem?: T;
  quantity?: T;
  priceAtPurchase?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  user?: T;
  menuItem?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  organizer?: T;
  name?: T;
  description?: T;
  type?: T;
  scope?: T;
  tags?: T;
  isOnline?: T;
  location?: T;
  poster?: T;
  quota?: T;
  registrationDeadline?: T;
  eventDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  ticketCode?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  creator?: T;
  competitionName?: T;
  field?: T;
  description?: T;
  deadline?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-positions_select".
 */
export interface TeamPositionsSelect<T extends boolean = true> {
  team?: T;
  positionName?: T;
  skillRequired?: T;
  slotsNeeded?: T;
  slotsFilled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-applications_select".
 */
export interface TeamApplicationsSelect<T extends boolean = true> {
  team?: T;
  position?: T;
  applicant?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-skills_select".
 */
export interface UserSkillsSelect<T extends boolean = true> {
  user?: T;
  skillName?: T;
  proficiency?: T;
  portfolioUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lost-items_select".
 */
export interface LostItemsSelect<T extends boolean = true> {
  reporter?: T;
  itemName?: T;
  category?: T;
  description?: T;
  lastSeenLocation?: T;
  lastSeenAt?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "found-items_select".
 */
export interface FoundItemsSelect<T extends boolean = true> {
  finder?: T;
  itemName?: T;
  category?: T;
  description?: T;
  foundLocation?: T;
  foundAt?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-matches_select".
 */
export interface ItemMatchesSelect<T extends boolean = true> {
  lostItem?: T;
  foundItem?: T;
  matchScore?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-chat-messages_select".
 */
export interface ItemChatMessagesSelect<T extends boolean = true> {
  match?: T;
  sender?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "majors_select".
 */
export interface MajorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-paths_select".
 */
export interface CareerPathsSelect<T extends boolean = true> {
  major?: T;
  title?: T;
  description?: T;
  relatedTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-skills_select".
 */
export interface CareerSkillsSelect<T extends boolean = true> {
  careerPath?: T;
  skillName?: T;
  resourceUrl?: T;
  isCertification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-career-progress_select".
 */
export interface UserCareerProgressSelect<T extends boolean = true> {
  user?: T;
  careerSkill?: T;
  isCompleted?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-actions_select".
 */
export interface AdminActionsSelect<T extends boolean = true> {
  admin?: T;
  actionType?: T;
  targetCollection?: T;
  targetId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}